siteinfo:
    description: Nosebit - Sua Idéia lá na Nuvem
    title: Nosebit
    keywords: startup,tech,chat
    #fb_app_id: 250528625300602
    mixpanel_key: 30b9a03d49ac92fa7e9eea918f88cba1
    #analytics_key: UA-79995910-2
    #optimizely_key: 5385733009
    #google_maps_key: AIzaSyDOko7oldevlasKPWl1x1sqZje1nzBZNvk
    base_url: //nosebit.com
    logo_icon_url: //nosebit.com/assets/images/logo_icon.png
    logo_favicon_url: //nosebit.com/assets/images/favicon.png

hostnames:
    webapp: nosebit.com
    api: api.nosebit.com
    socket: socket.nosebit.com